### ISSUE TITLE
[Request] Can "lava flow backwards?"

### ISSUE THREAD

**Issue by MeatSpaceCD** [Praxxian/lava-flow#12]
I have a library of journal entries prepped in Foundry already, but I would like to make the move to Obsidian's more powerful system. I'd love to take advantage of both apps by utilizing lava-flows as one stop shop. How difficult would it be to convert my existing Journal Entries into Obsidian markdown files, to then use that database of Obsidian files to populate Foundry?

**Comment by Praxxian** [comment]
The good news is that there is an Obsidian plugin that does this! 

https://github.com/farling42/obsidian-import-foundry

I've not used it. Let me know how this works out for you.

**Comment by Praxxian** [comment]
Closing this issue. Hope that Obsidian plugin worked out for you. If not, let me know!
