### ISSUE TITLE
[Request] Remember top level folder

### ISSUE THREAD

**Issue by OfficerHalf** [Praxxian/lava-flow#2]
It would be a huge usability improvement if the top level foundry folder was configurable via settings or was just remembered between imports. I plan on using this to keep my handouts in Obsidian in sync with handouts in Foundry, and it seems to do that very well, but that would make it nearly perfect.

🙏 bless you for this, seriously. And come chat in the Obsidian discord, the tabletop-games channel is a great group. 🙂

**Comment by Praxxian** [comment]
[Version 1.0.2](https://github.com/Praxxian/lava-flow/releases/tag/1.0.2) now has this feature.
