### ISSUE TITLE
Can't pick any files or folders.

### ISSUE THREAD

**Issue by Sandman2055** [Praxxian/lava-flow#21]
When attempting to Import Obsidian MD Vault using the button in the Journal area of Foundry, the dialog box will allow browsing to my vault, but will not accept folders.  I get a message saying "Please select one or more files".  Files aren't showing up at all when I click 'Choose Files'.

Also, the small ? info  icons do nothing when clicked.

**Comment by ZRTAssassin** [comment]
Happens to me as well.

Tested in a fresh world using version 9 of Foundry with version 1.1.2 of Lava Flow.

![Imgur](https://imgur.com/kYeuKwE.gif)

**Comment by Praxxian** [comment]
@ZRTAssassin There is an issue in v9 with the version of Electron that Foundry uses. Please try to using the module in Chrome or Firefox.

@Sandman2055 I know you said you were using v10 in discord. Was this an upgrade from v9 or a new install? Also let me know if Chrome or Firefox works for you.

**Comment by ZRTAssassin** [comment]
@Praxxian Worked fine using chrome. Thanks a bunch.

**Comment by Praxxian** [comment]
Confirmed on discord that a v10 installer resolves the issue for the desktop app.
