### ISSUE TITLE
Images with spaces don't work

### ISSUE THREAD

**Issue by Sinled** [Praxxian/lava-flow#22]
Hi, thanks for great addon

It seems if you have images with spaces they are not processed correctly, 
such images displayed as simple text

<img width="400" alt="Screenshot 2023-01-02 at 19 40 47" src="https://user-images.githubusercontent.com/1402135/210264106-c6ccd3fc-21e9-4fb5-9134-4f8019b9c047.png">

also, is there any chances of implementing custom width for images?

**Comment by Praxxian** [comment]
I think the issue might be with the alt text format. It is only matching images on ![[path/to/img.png]].

Foundry uses showdown for markdown-to-html, and it does support custom image widths, but I am not sure if they let you set the dimensions using the width only like Obsidian does. I'll look into it!

**Comment by Praxxian** [comment]
Oh it looks like the space is also a problem. Might be something with showdown. Now I've found two issues!

**Comment by Sinled** [comment]
>  but I am not sure if they let you set the dimensions using the width only like Obsidian does


just checked, if you edit imported file, and add ` =200x*` to file path, it will render image with corresponding width value on image

```
### Resized
![obsidian_banner.png](assets/cos/uploads/obsidian_banner.png =200x*)
```

**Comment by Praxxian** [comment]
If you update to the latest version 2.1.0 (not to be confused with 2.0.1) this should be resolved. Added in support for resizing images, too!
