### ISSUE TITLE
Request: page usage

### ISSUE THREAD

**Issue by maxobremer** [Praxxian/lava-flow#23]
Hey don't know if this is a feature yet, but I couldn't find anything about it. Is it possible to have an obsidian folder be turned into a journal entry and the different notes within that folder become pages within that journal entry instead of each of the journal entries? Of course talking about version 10 of foundry

**Comment by maxobremer** [comment]
Maybe if a folder starts with a certain marker in its name like FoundryJournalEntryWithPages idk

**Comment by Praxxian** [comment]
I have thought about this functionality, but wanted to save implementing it after I got v10 compatibility working. Still not sure totally how I want to implement and what would be the most user-friendly.

This could be done in a few of ways to designate this (not mutually exclusive):
- Universal setting: any folder that _only_ contains notes becomes a journal entry with several pages.
- By tag in one of the files within the folder.
- By adding an attribute in one of the file's YAML.

**Comment by vt-tom** [comment]
I would really like to see this implementation. Because foundry can't seht pins on the scene for headings (without modules)
So I would like to habe them separated as pages.

I think in my case a yaml flag would help much:
pages: "heading2"

So all heading 2 lines get separated in pages.

**Comment by SomeOats** [comment]
The approach I've taken is to leverage the headers in each page. I have a global setting to either import markdown pages as is or to split the page based on the header into Foundry JournalEntry pages. 

The markdown page is split on the h1 line. This header becomes the page name and each subsequent header moves up one (h2 -> h1, h3 -> h2, etc). 

My folder structure matches between Obsidian and Foundry, while Obsidian notes match to Foundry JournalEntries. 

I have a rough working branch at [headerToPage](https://github.com/SomeOats/lava-flow/tree/headerToPage), although it includes several other changes (option to create root folder or not and ability to link to headers). It's not fully tested yet.

**Comment by Praxxian** [comment]
Just released Version 3.1.0, which includes this feature. The import dialog includes an option called `Combine notes into pages?` which will do this for any folder that contains only notes and no subfolders. There is another checkbox under it to disable this condition, allowing you to combine notes wherever. Not totally sure who would desire this or why I spent time on it, but there you go.

Thanks all for your feedback!
