### ISSUE TITLE
[Request]: Ignore YAML metadata on import

### ISSUE THREAD

**Issue by sirgawain111** [Praxxian/lava-flow#25]
On import, the YAML metadata entries in the "header section" such as aliases, tags, etc. are (partly) imported as \<h2> paragraphs. Would it be possible to completely ignore those entries on import?

Obsidian file:
![grafik](https://user-images.githubusercontent.com/85822812/216967944-f323a369-94da-418a-8c83-82b7ef001d28.png)

Foundry journal entry:
![grafik](https://user-images.githubusercontent.com/85822812/216968091-5ac02bea-d470-43fb-9c7d-35ed976f3a73.png)

**Comment by joetheory** [comment]
This plugin is an absolute game-changer for me! Thank you so much!  I am having this same issue-  Tags are super useful in Obsidian but don't really help at all in Foundry.  Aliases could be useful but I don't know how you could implement them other than duplicate entries.  I think the best thing to do for now would be to just check for the --- --- and strip or ignore it completely.

**Comment by Praxxian** [comment]
Something interesting is that showdown, the markdown converter that Foundry implemented, does have an option to ignore metadata, but it is off by default. Might merely be a matter of seeing if I can enable that. That would be ideal vs actually changing the content of the note as it is imported.

**Comment by Praxxian** [comment]
This issue along with a few others has been fixed in release 2.2.0. Please upgrade your module and let me know if you experience any more unexpected behavior. Thanks!
