### ISSUE TITLE
Layout issue with the "The Dark Eye" system

### ISSUE THREAD

**Issue by sirgawain111** [Praxxian/lava-flow#26]
The system "Das Schwarze Auge/The Dark Eye (5th Edition)" (https://github.com/Plushtoast/dsa5-foundryVTT) adds an additional button to the Journals pane.

![grafik](https://user-images.githubusercontent.com/85822812/218454153-4773f5de-36e8-4ce1-a929-ef9e5e9219e9.png)

<br />This button dissappears when activating Lava Flow.

![grafik](https://user-images.githubusercontent.com/85822812/218453661-f15f0416-0858-4c20-8aa5-98d00de2dfe9.png)

**Comment by Praxxian** [comment]
Oh, that's strange. I just prepends the button to that area, so I am not sure what is going on with the other button. Should be easy to reproduce, though, so I will give it a shot!

**Comment by Praxxian** [comment]
Just an update that I do have a fix for the issue. I am going to try to bundle that in a release with some other fixes. If those other fixes take too long, I might just release this on its own.

**Comment by sirgawain111** [comment]
Great to hear, thanky you!

**Comment by Praxxian** [comment]
This issue along with a few others has been fixed in release 2.2.0. Please upgrade your module and let me know if you experience any more unexpected behavior. Thanks!
