### ISSUE TITLE
Links to headers and linking with other names

### ISSUE THREAD

**Issue by joetheory** [Praxxian/lava-flow#27]
I make pretty extensive use of header linking and obfuscating names by linking with others in Markdown.  Lava-Flow doesn't seem to account for this currently and I would love to see this factored in.  I have included some examples images to show what I am referring to.

![Screenshot 2023-02-17 095749](https://user-images.githubusercontent.com/64994/219692926-6b39314b-e253-4512-9197-77600554d761.png)

![Screenshot 2023-02-17 095823](https://user-images.githubusercontent.com/64994/219692952-23e42415-687d-45f6-bd4f-ff8dcfa01d23.png)

![Screenshot 2023-02-17 100636](https://user-images.githubusercontent.com/64994/219693160-1f14e202-e853-4881-9c83-4f45d64a0d48.png)

![Screenshot 2023-02-17 100251](https://user-images.githubusercontent.com/64994/219692993-cbb90490-2544-4397-8f4a-6b3ab37b3f10.png)

**Comment by joetheory** [comment]
You should be able to see the examples in Read and Edit view of Obsidian and then the example of how they appear in Edit and read mode of Foundry after import.

**Comment by Praxxian** [comment]
Thanks for the steps to reproduce the issue. Pretty cut and dry.

**Comment by Praxxian** [comment]
This issue along with a few others has been fixed in release 2.2.0. Please upgrade your module and let me know if you experience any more unexpected behavior. Thanks!
