### ISSUE TITLE
Not respecting links

### ISSUE THREAD

**Issue by anthonydeaver** [Praxxian/lava-flow#3]
I installed this a couple days ago and imported my Obsidian vault, when I looked at the pages in the Journal none of the links were maintained, they were all text. Is there only a certain format the plugin expects for links?
![Screenshot_122121_054958_PM](https://user-images.githubusercontent.com/638054/147259842-67ad8433-4641-4546-8c89-77c9ec6c0210.jpg)

**Comment by anthonydeaver** [comment]
The page in Obsidian
![Screenshot_122121_054934_PM](https://user-images.githubusercontent.com/638054/147259892-98a3fbdd-c97e-4008-9cfb-998a3960e3d5.jpg)

**Comment by Praxxian** [comment]
Thanks for providing those screenshots! That helps a ton. Nothing seems wrong with those links just from looking at them.

I have to ask the obvious just in case: were the notes associated to those links imported as well? This could happen if you import a subfolder and it contains links that were not imported.

**Comment by anthonydeaver** [comment]
Side by Side in Foundry and Obsidian. I'm assuming the one in Foundry is/was the one in Obsidian. :)

Showing the obsidian versions in edit mode so you can see that the data in both files match. Also figured edit mode might show anything 'off'.

What I find really odd is in both pages, the link to the Eberron 'parent' page (the page under which all the imported files belong) _is_ linked. But that's the only one.

![Screenshot_122321_072413_PM](https://user-images.githubusercontent.com/638054/147301689-a72fbb33-aa0f-442a-b136-f2232e734194.jpg)
![Screenshot_122321_072524_PM](https://user-images.githubusercontent.com/638054/147301690-776e48fc-09b6-4b0f-a019-7d5a9cbd2ec1.jpg)

**Comment by Praxxian** [comment]
Did you receive an "import complete" message? I am wondering if there is some underlying bug that stopped the link replacement from completing.

I did fix one bug. Could you please try upgrading the module to the latest version and seeing if you can still reproduce the issue?

**Comment by anthonydeaver** [comment]
Negative, same result. Even deleted that world and created a new one and reimported. Same pages, same results, no linkage.

**Comment by anthonydeaver** [comment]
Just saw you question about the "Import Complete" messaged so I created another world and imported again, this time with the debug console open. Sure enough, it threw an error in the console:

`SyntaxError: Invalid regular expression: /\[\[(Calendar|Eberron/Modules/Eberron Campaign Setting (3)\]\]/: Unterminated group
    at new RegExp (<anonymous>)
    at MDFileInfo.getKeyRegex (lava-flow.js:313)
    at Function.updateLinks (lava-flow.js:210)
    at Function.importVault (lava-flow.js:77)
    at async LavaFlowConfig._updateObject (lava-flow.js:260)
    at async LavaFlowConfig._onSubmit (foundry.js:3822)`

So I did some further digging. The files it's complaining about below is actually titled _Eberron Campaign Setting (3.5)_. I renamed it, removing the _(3.5)_ and everything imported without issue. 

At first I thought it might not like the extra period in 3.5 so I renamed another file, adding an extra couple of periods but that also imported without issue. So I then renamed another file called Forgotten Forge to Forgotten Forge (3.5) and it failed again with the same error message as above, 'Unterminated group'

 It doesn't like having a period (a.k.a. 'separator') inside the parens. I'm guessing that on line 309 in lava-flow.js, when you split on the separator for this filename it's returning _Eberron Campaign Setting (3._ as the fullKey which the regex freaks out about because of the open paren.
 
 I can easily work around this by removing the '(3.5)'. I don't know if a lot of people will do things like this,  but it's something to maybe think about in the future. At least for cases when someone else reports the issue :)
 
 Anyway, great work!

**Comment by Praxxian** [comment]
My next suggestion was going to be to open the console, so thanks for anticipating!

Yeah I need to do some regex escaping. You shouldn't have to remove that stuff for it to work. I'll update when I have a fix for that, but glad to hear you have a workaround.

**Comment by Praxxian** [comment]
Release 1.0.3 resolves this issue. Thanks for your feedback!
