### ISSUE TITLE
Player Observer Permissions Aren't Being Set In Subfolders

### ISSUE THREAD

**Issue by joetheory** [Praxxian/lava-flow#36]
I have my player compendium entries in folders for organization as below:
![image](https://user-images.githubusercontent.com/64994/223843231-7e74cc8f-257e-46b3-9dad-74ae9d6ebef7.png)

Entries in the root get the correct permissions on import but subfolders (Creatures and Races, Objects and Other, etc.) do not.  It's easy enough to right click and update each folder after import but I suppose it would be an enhancement to make sure subfolder entries get set as well.

**Comment by Praxxian** [comment]
Hi there and sorry for the long wait on this issue. Should be pretty easy to reproduce, but I will let you know if I have any trouble.

**Comment by joetheory** [comment]
Awesome, this one is more of a QoL fix for me.  I have 6 or so subfolders and I just have to reset the perms on each every time I upload.  Not a big deal but would be if more folders arise. :)  Thanks again.

**Comment by Praxxian** [comment]
Fixed in 4.1.0
