### ISSUE TITLE
Lava-flow not able to upload images

### ISSUE THREAD

**Issue by kuchrk24** [Praxxian/lava-flow#40]
Foundry v11.306
Lava-flow v 3.0.0

I am running Foundry in a docker container. I have left the upload path as default (img). Lava-flow seems to be having an issue with uploading.

![image](https://github.com/Praxxian/lava-flow/assets/74018852/097904a4-3924-4814-be4f-b784b9c025a9)
![image](https://github.com/Praxxian/lava-flow/assets/74018852/7c3aeab4-b200-4ced-adb1-d1f4cafb95c4)

**Comment by kuchrk24** [comment]
Oh I see. I created that folder and it's fine. Would be nice for the module to create the folder if it didn't exist.

**Comment by Praxxian** [comment]
Fixed in release 3.0.2.
