### ISSUE TITLE
Running Import periodically? 

### ISSUE THREAD

**Issue by orangebutblue** [Praxxian/lava-flow#41]
Is it possibly to automate the import process and having it run periodically (maybe with a cronjob)?

Ideally, I just want to add notes to my obsidian vault and then simply open up foundry at some point and have my newest notes there already waiting for me (without having to go through the manual user interaction of importing the notes by hand)

**Comment by Praxxian** [comment]
I certainly sympathize with the desire for automation, but I think this is outside the scope of a Foundry module. I am not sure if there are server-side modules. If you happen to know of any modules that work this way, I would be interested to know.

Modules are client-side, and for very good reasons, can't just directly access your file system on their own. It interacts with server data through Foundry's API. For this to work, you would need your vault on the same computer as your foundry instance, which is not the case for everyone, and the API would need to provide a way to specify a folder and retrieve all files recursively. I know there is a FilePicker class, so maybe that's possible. I will do a little research.

**Comment by orangebutblue** [comment]
Do you think it's not possible/dangerous to just load the journal.db json file and update it with the new notes?

**Comment by Praxxian** [comment]
I would not advise editing journal.db directly. This should be done through the API to avoid corrupting the file.
