### ISSUE TITLE
Obsidian links to non-existant notes display as null in Foundry journal

### ISSUE THREAD

**Issue by kuchrk24** [Praxxian/lava-flow#43]
Would be nice if it would build those as the text of the link without the reference to another journal.

![image](https://github.com/Praxxian/lava-flow/assets/74018852/09e661e8-09f4-4dba-91fc-91ed3e024a84)
![image](https://github.com/Praxxian/lava-flow/assets/74018852/3fc00f90-8327-47ed-a65b-87fe228584b0)

**Comment by Praxxian** [comment]
Yeah I'll need to add this scenario to the test vault so I don't break this in the future. Clearly unexpected behavior during the link conversion process.

**Comment by captaingoodnight** [comment]
At least as far as images go, if you use an S3 compatible service from anyone other than AW, the endpoint naming convention is different so the link points to the wrong place.

Currently, you hardcode `s3` and `amazonaws.com` in the link.
path = `https://${settings.s3Bucket}.s3.${settings.s3Region}.amazonaws.com/${path}`; 

For a service like DigitalOcean, their endpoint name is 
https:\\{s3Bucket}.{s3Region}.digitaloceanspaces.com

Kind of a pain to have to support multiple providers with different naming conventions.

**Comment by Praxxian** [comment]
@kuchrk24 are you able to reproduce this behavior on the latest version? I cannot. I think this was fixed along with several things.

@captaingoodnight I think the S3 issue got resolved via another ticket. I did not have the `FilePicker` implemented incorrectly. So if you are able to use alternative services in your foundry config, it should work. Can you try this on the latest module version? Thanks!

**Comment by kuchrk24** [comment]
Yes, it just shows the name now. Much better, thank you.

![image](https://github.com/Praxxian/lava-flow/assets/74018852/33882cfc-54f8-45a4-a214-07e57bac582b)
