### ISSUE TITLE
No files importing Version 10 - Docker

### ISSUE THREAD

**Issue by Runesmite** [Praxxian/lava-flow#44]
Hello, I am experiencing an odd issue.

## Issue
Files will not import/upload
- Foundry Version: 10.303
  - linux/node.js version
- DnD5e Version: 2.3.1

## Description
I see in the Readme that there is a possible issue with no files loading in when you import on version 10 foundries that have been updated. I host my Foundry using Docker and Felddy's image.

I have deleted my foundry image (container_cache) and even replaced my world.json with a fresh one from a brand new World built in Foundry 10. My campaign has been going since v9.

No matter what, nothing imports at all. It can create an empty Index but that's it. All I can find in the ReadMe is to do a fresh install, which to my knowlege I have. If you have any ideas as to why this isn't working or anything I could test I'd appreciate it.

## Obsidian Notes
I am using icloud to sync my obsidian notes, but I've also tried copying the folder and moving it to a drive outside of cloud storage. There are .md files in the folders I am importing, but they do not show up in Foundry.

## Other Notes
I have not updated to Foundry v11 yet as there are other modules that I use, particularly token attacher and vehicles, that only work in V10 for now.

## Additional Testing
I have disabled all other modules, and the issue persists.

**Comment by Runesmite** [comment]
Well then, I think I figured it out. It's the browser I was using. I am using OperaGX and it seems that whatever workflow Lava Flow uses to upload files it doesn't like.

I opened Edge to try it out and when I chose the folder to upload, Edge prompted me asking if I wanted to upload files to which I agreed to and voila, the Lava Flow menu even reported 13 files to upload - something which hadn't been happending with OperaGX.

I guess I'll be using Edge in the meantime then.

**Comment by Praxxian** [comment]
Great job on figuring this out yourself! Different browser would have been my first suggestion. Not all browsers support the folder-picker. That was the underlying issue in v9/10 when using the app instead of a browser.

Not really much I can do, but I will update the README to call this out.
