### ISSUE TITLE
Feature Request: Option to Create Single Journal with Multiple Pages Rather Than One Journal per Page

### ISSUE THREAD

**Issue by claycle** [Praxxian/lava-flow#48]
As an option to the normal behavior:

Rather than creating a 1-to-1 relationship between Obsidian vault MD files and Foundry Journal entries, give an option to create a vault folder as journal entry that contains multiple pages (the MD files). Place the Index entry, if created, as page 0 in the new journal.

This breaks a bit if the original Obsidian vault folder contains sub-folders itself. In that case, create the subfolder in Foundry, but place a single collated journal of entries in it.

**Comment by Praxxian** [comment]
Thanks for your feedback! This duplicates #23, so I am going to close this one.
