### ISSUE TITLE
Folder Structure Not Being Imported

### ISSUE THREAD

**Issue by SetArk** [Praxxian/lava-flow#62]
Well, i think it's a simple concept.
I have an "Entities" Folder.
Under it, i have "Subfolders"/ "Deities", "Patrons", "Saints" , "Important Fiends", "Important Celestials", "Purposes" 
And on each one there's at least one note with some character i described.

Lava-Flow as far as i understood, would put te subfolders, inside the main Folder "Entities". 

For some reason, it's spreading all folders separately. 
I tried various combinations of settings but, it just doesn't work.

**Comment by Centor1982** [comment]
Having the same issue but in v12 so maybe that is the issue.

**Comment by carolinex** [comment]
Same as documented here
https://github.com/Praxxian/lava-flow/issues/59

**Comment by Praxxian** [comment]
Will be fixed in #59.
